import type { VehicleItemDefinition } from "./inventory.types";

export const vehicleCatalog: readonly VehicleItemDefinition[] = [
  {
    id: "bicycle",
    name: "Bicycle",
    type: "vehicle",
    category: "garage",
    price: 150,
    unlockLevel: 1,
    respectBonus: 0,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "motorbike",
    name: "Motorbike",
    type: "vehicle",
    category: "garage",
    price: 900,
    unlockLevel: 2,
    respectBonus: 1,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "compact-car",
    name: "Compact Car",
    type: "vehicle",
    category: "garage",
    price: 3000,
    unlockLevel: 3,
    respectBonus: 2,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "sedan",
    name: "Sedan",
    type: "vehicle",
    category: "garage",
    price: 7500,
    unlockLevel: 5,
    respectBonus: 3,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "muscle-car",
    name: "Muscle Car",
    type: "vehicle",
    category: "garage",
    price: 20000,
    unlockLevel: 7,
    respectBonus: 6,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "sports-car",
    name: "Sports Car",
    type: "vehicle",
    category: "garage",
    price: 50000,
    unlockLevel: 9,
    respectBonus: 10,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "pickup-truck",
    name: "Pickup Truck",
    type: "vehicle",
    category: "garage",
    price: 60000,
    unlockLevel: 10,
    respectBonus: 8,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "luxury-car",
    name: "Luxury Car",
    type: "vehicle",
    category: "garage",
    price: 110000,
    unlockLevel: 12,
    respectBonus: 15,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "supercar",
    name: "Supercar",
    type: "vehicle",
    category: "garage",
    price: 275000,
    unlockLevel: 15,
    respectBonus: 22,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "suv",
    name: "SUV",
    type: "vehicle",
    category: "garage",
    price: 420000,
    unlockLevel: 17,
    respectBonus: 18,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "armored-car",
    name: "Armored Car",
    type: "vehicle",
    category: "garage",
    price: 750000,
    unlockLevel: 19,
    respectBonus: 28,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "exotic-hypercar",
    name: "Exotic Hypercar",
    type: "vehicle",
    category: "garage",
    price: 2000000,
    unlockLevel: 21,
    respectBonus: 40,
    parkingSlots: null,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  }
];
