import type { PropertyItemDefinition } from "./inventory.types";

export const propertyCatalog: readonly PropertyItemDefinition[] = [
  {
    id: "rented-garage",
    name: "Rented Garage",
    type: "property",
    category: "realestate",
    price: 500,
    unlockLevel: 1,
    respectBonus: 0,
    parkingSlots: 1,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "studio-apartment",
    name: "Studio Apartment",
    type: "property",
    category: "realestate",
    price: 2000,
    unlockLevel: 2,
    respectBonus: 1,
    parkingSlots: 0,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "apartment",
    name: "Apartment",
    type: "property",
    category: "realestate",
    price: 6000,
    unlockLevel: 4,
    respectBonus: 3,
    parkingSlots: 1,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "row-house",
    name: "Row House",
    type: "property",
    category: "realestate",
    price: 18000,
    unlockLevel: 6,
    respectBonus: 6,
    parkingSlots: 2,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "suburban-house",
    name: "Suburban House",
    type: "property",
    category: "realestate",
    price: 50000,
    unlockLevel: 9,
    respectBonus: 10,
    parkingSlots: 3,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "city-condo",
    name: "City Condo",
    type: "property",
    category: "realestate",
    price: 90000,
    unlockLevel: 11,
    respectBonus: 14,
    parkingSlots: 2,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "luxury-villa",
    name: "Luxury Villa",
    type: "property",
    category: "realestate",
    price: 250000,
    unlockLevel: 14,
    respectBonus: 20,
    parkingSlots: 4,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "penthouse-suite",
    name: "Penthouse Suite",
    type: "property",
    category: "realestate",
    price: 600000,
    unlockLevel: 17,
    respectBonus: 30,
    parkingSlots: 3,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  },
  {
    id: "country-estate",
    name: "Country Estate",
    type: "property",
    category: "realestate",
    price: 1500000,
    unlockLevel: 20,
    respectBonus: 50,
    parkingSlots: 6,
    delivery: "inventory",
    equipSlot: null,
    weaponStats: null,
    armorStats: null,
    consumableEffects: null
  }
];
