"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

import type { Player, PlayerActivity } from "../lib/api-types";
import { ApiError } from "../lib/api-client";
import { formatDateTime, formatMoney } from "../lib/formatters";
import { gameApi } from "../lib/game-api";
import { AppShell } from "./app-shell";
import { useSession } from "./providers/session-provider";

export function DashboardPage() {
  const { accessToken, account } = useSession();
  const [player, setPlayer] = useState<Player | null>(null);
  const [activity, setActivity] = useState<PlayerActivity[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function loadData() {
      if (!accessToken || !account?.player?.id) {
        return;
      }

      setIsLoading(true);
      setError(null);

      try {
        const [nextPlayer, nextActivity] = await Promise.all([
          gameApi.players.getById(account.player.id),
          gameApi.activity.listCurrent(accessToken, 5)
        ]);

        setPlayer(nextPlayer);
        setActivity(nextActivity);
      } catch (nextError) {
        setError(
          nextError instanceof ApiError
            ? nextError.message
            : "Unable to load dashboard data."
        );
      } finally {
        setIsLoading(false);
      }
    }

    void loadData();
  }, [accessToken, account?.player?.id]);

  return (
    <AppShell
      title="Dashboard"
      subtitle="Current player status and the shortest path into the playable prototype loop."
    >
      {error ? <p className="notice notice-error">{error}</p> : null}

      <section className="dashboard-grid">
        <article className="panel">
          <p className="eyebrow">Player</p>
          <h2>{player?.displayName ?? "Loading player"}</h2>
          <dl className="stats-grid">
            <div>
              <dt>Cash</dt>
              <dd>{player ? formatMoney(player.cash) : "..."}</dd>
            </div>
            <div>
              <dt>Respect</dt>
              <dd>{player?.respect ?? "..."}</dd>
            </div>
            <div>
              <dt>Energy</dt>
              <dd>{player?.energy ?? "..."}</dd>
            </div>
            <div>
              <dt>Health</dt>
              <dd>{player?.health ?? "..."}</dd>
            </div>
            <div>
              <dt>Jailed until</dt>
              <dd>{formatDateTime(player?.jailedUntil ?? null)}</dd>
            </div>
            <div>
              <dt>Hospitalized until</dt>
              <dd>{formatDateTime(player?.hospitalizedUntil ?? null)}</dd>
            </div>
          </dl>
        </article>

        <article className="panel">
          <p className="eyebrow">Quick routes</p>
          <h2>Playable slice</h2>
          <div className="shortcut-list">
            <Link className="shortcut-card" href="/crimes">
              Run crimes and consume energy through `/api/me/crimes/*`.
            </Link>
            <Link className="shortcut-card" href="/inventory">
              Buy starter items and manage equipment slots.
            </Link>
            <Link className="shortcut-card" href="/missions">
              Accept and complete missions from current progress state.
            </Link>
            <Link className="shortcut-card" href="/activity">
              Read the persistent activity feed generated by backend events.
            </Link>
          </div>
        </article>
      </section>

      <section className="panel">
        <p className="eyebrow">Recent activity</p>
        <h2>Latest feed entries</h2>
        {isLoading ? (
          <p className="muted">Loading activity...</p>
        ) : activity.length > 0 ? (
          <ul className="list">
            {activity.map((entry) => (
              <li key={entry.id} className="list-item">
                <div>
                  <strong>{entry.title}</strong>
                  <p className="muted">{entry.body}</p>
                </div>
                <span className="meta">{formatDateTime(entry.createdAt)}</span>
              </li>
            ))}
          </ul>
        ) : (
          <p className="muted">No activity has been generated for this player yet.</p>
        )}
      </section>
    </AppShell>
  );
}
