"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.weaponUnlockCatalog = void 0;
const defaultWeaponUnlockCatalog = [
    {
        id: "rusty-knife",
        name: "Glock 17",
        type: "weapon",
        category: "handguns",
        price: 400,
        equipSlot: "weapon",
        unlockLevel: 1,
        weaponStats: { damageBonus: 4 },
        armorStats: null
    },
    {
        id: "cheap-pistol",
        name: "Colt M1911",
        type: "weapon",
        category: "handguns",
        price: 1800,
        equipSlot: "weapon",
        unlockLevel: 1,
        weaponStats: { damageBonus: 8 },
        armorStats: null
    },
    {
        id: "beretta-92fs",
        name: "Beretta 92FS",
        type: "weapon",
        category: "handguns",
        price: 2400,
        equipSlot: "weapon",
        unlockLevel: 2,
        weaponStats: { damageBonus: 9 },
        armorStats: null
    },
    {
        id: "walther-p38",
        name: "Walther P38",
        type: "weapon",
        category: "handguns",
        price: 2550,
        equipSlot: "weapon",
        unlockLevel: 2,
        weaponStats: { damageBonus: 10 },
        armorStats: null
    },
    {
        id: "sig-sauer-p226",
        name: "SIG Sauer P226",
        type: "weapon",
        category: "handguns",
        price: 3000,
        equipSlot: "weapon",
        unlockLevel: 3,
        weaponStats: { damageBonus: 11 },
        armorStats: null
    },
    {
        id: "cz-75",
        name: "CZ 75",
        type: "weapon",
        category: "handguns",
        price: 3150,
        equipSlot: "weapon",
        unlockLevel: 3,
        weaponStats: { damageBonus: 12 },
        armorStats: null
    },
    {
        id: "heckler-koch-usp",
        name: "Heckler & Koch USP",
        type: "weapon",
        category: "handguns",
        price: 3600,
        equipSlot: "weapon",
        unlockLevel: 4,
        weaponStats: { damageBonus: 13 },
        armorStats: null
    },
    {
        id: "walther-ppk",
        name: "Walther PPK",
        type: "weapon",
        category: "handguns",
        price: 3750,
        equipSlot: "weapon",
        unlockLevel: 4,
        weaponStats: { damageBonus: 14 },
        armorStats: null
    },
    {
        id: "fn-five-seven",
        name: "FN Five-seveN",
        type: "weapon",
        category: "handguns",
        price: 4300,
        equipSlot: "weapon",
        unlockLevel: 5,
        weaponStats: { damageBonus: 15 },
        armorStats: null
    },
    {
        id: "springfield-xd",
        name: "Springfield XD",
        type: "weapon",
        category: "handguns",
        price: 4450,
        equipSlot: "weapon",
        unlockLevel: 5,
        weaponStats: { damageBonus: 16 },
        armorStats: null
    },
    {
        id: "desert-eagle",
        name: "Desert Eagle",
        type: "weapon",
        category: "handguns",
        price: 5200,
        equipSlot: "weapon",
        unlockLevel: 6,
        weaponStats: { damageBonus: 18 },
        armorStats: null
    },
    {
        id: "tokarev-tt-33",
        name: "Tokarev TT-33",
        type: "weapon",
        category: "handguns",
        price: 4950,
        equipSlot: "weapon",
        unlockLevel: 6,
        weaponStats: { damageBonus: 17 },
        armorStats: null
    },
    {
        id: "mac-10",
        name: "MAC-10",
        type: "weapon",
        category: "smg",
        price: 5400,
        equipSlot: "weapon",
        unlockLevel: 6,
        weaponStats: { damageBonus: 19 },
        armorStats: null
    },
    {
        id: "mp5",
        name: "MP5",
        type: "weapon",
        category: "smg",
        price: 6200,
        equipSlot: "weapon",
        unlockLevel: 7,
        weaponStats: { damageBonus: 20 },
        armorStats: null
    },
    {
        id: "uzi",
        name: "Uzi",
        type: "weapon",
        category: "smg",
        price: 6350,
        equipSlot: "weapon",
        unlockLevel: 7,
        weaponStats: { damageBonus: 21 },
        armorStats: null
    },
    {
        id: "mac-11",
        name: "MAC-11",
        type: "weapon",
        category: "smg",
        price: 6500,
        equipSlot: "weapon",
        unlockLevel: 7,
        weaponStats: { damageBonus: 22 },
        armorStats: null
    },
    {
        id: "mp40",
        name: "MP40",
        type: "weapon",
        category: "smg",
        price: 7200,
        equipSlot: "weapon",
        unlockLevel: 8,
        weaponStats: { damageBonus: 23 },
        armorStats: null
    },
    {
        id: "thompson",
        name: "Thompson",
        type: "weapon",
        category: "smg",
        price: 7350,
        equipSlot: "weapon",
        unlockLevel: 8,
        weaponStats: { damageBonus: 24 },
        armorStats: null
    },
    {
        id: "sten",
        name: "Sten",
        type: "weapon",
        category: "smg",
        price: 7500,
        equipSlot: "weapon",
        unlockLevel: 8,
        weaponStats: { damageBonus: 25 },
        armorStats: null
    },
    {
        id: "p90",
        name: "P90",
        type: "weapon",
        category: "smg",
        price: 8300,
        equipSlot: "weapon",
        unlockLevel: 9,
        weaponStats: { damageBonus: 26 },
        armorStats: null
    },
    {
        id: "mp7",
        name: "MP7",
        type: "weapon",
        category: "smg",
        price: 8450,
        equipSlot: "weapon",
        unlockLevel: 9,
        weaponStats: { damageBonus: 27 },
        armorStats: null
    },
    {
        id: "sterling",
        name: "Sterling",
        type: "weapon",
        category: "smg",
        price: 8600,
        equipSlot: "weapon",
        unlockLevel: 9,
        weaponStats: { damageBonus: 28 },
        armorStats: null
    },
    {
        id: "ump45",
        name: "UMP45",
        type: "weapon",
        category: "smg",
        price: 9500,
        equipSlot: "weapon",
        unlockLevel: 10,
        weaponStats: { damageBonus: 29 },
        armorStats: null
    },
    {
        id: "ppsh-41",
        name: "PPSh-41",
        type: "weapon",
        category: "smg",
        price: 9650,
        equipSlot: "weapon",
        unlockLevel: 10,
        weaponStats: { damageBonus: 30 },
        armorStats: null
    },
    {
        id: "aks-74u",
        name: "AKS-74U",
        type: "weapon",
        category: "assault_rifle",
        price: 9900,
        equipSlot: "weapon",
        unlockLevel: 10,
        weaponStats: { damageBonus: 31 },
        armorStats: null
    },
    {
        id: "ak-47",
        name: "AK-47",
        type: "weapon",
        category: "assault_rifle",
        price: 11000,
        equipSlot: "weapon",
        unlockLevel: 11,
        weaponStats: { damageBonus: 32 },
        armorStats: null
    },
    {
        id: "ak-74",
        name: "AK-74",
        type: "weapon",
        category: "assault_rifle",
        price: 11150,
        equipSlot: "weapon",
        unlockLevel: 11,
        weaponStats: { damageBonus: 33 },
        armorStats: null
    },
    {
        id: "m16",
        name: "M16",
        type: "weapon",
        category: "assault_rifle",
        price: 11300,
        equipSlot: "weapon",
        unlockLevel: 11,
        weaponStats: { damageBonus: 34 },
        armorStats: null
    },
    {
        id: "m4-carbine",
        name: "M4 Carbine",
        type: "weapon",
        category: "assault_rifle",
        price: 12600,
        equipSlot: "weapon",
        unlockLevel: 12,
        weaponStats: { damageBonus: 35 },
        armorStats: null
    },
    {
        id: "fn-scar",
        name: "FN SCAR",
        type: "weapon",
        category: "assault_rifle",
        price: 12750,
        equipSlot: "weapon",
        unlockLevel: 12,
        weaponStats: { damageBonus: 36 },
        armorStats: null
    },
    {
        id: "steyr-aug",
        name: "Steyr AUG",
        type: "weapon",
        category: "assault_rifle",
        price: 12900,
        equipSlot: "weapon",
        unlockLevel: 12,
        weaponStats: { damageBonus: 37 },
        armorStats: null
    },
    {
        id: "heckler-koch-g36",
        name: "Heckler & Koch G36",
        type: "weapon",
        category: "assault_rifle",
        price: 14300,
        equipSlot: "weapon",
        unlockLevel: 13,
        weaponStats: { damageBonus: 38 },
        armorStats: null
    },
    {
        id: "heckler-koch-hk416",
        name: "Heckler & Koch HK416",
        type: "weapon",
        category: "assault_rifle",
        price: 14450,
        equipSlot: "weapon",
        unlockLevel: 13,
        weaponStats: { damageBonus: 39 },
        armorStats: null
    },
    {
        id: "famas",
        name: "FAMAS",
        type: "weapon",
        category: "assault_rifle",
        price: 14600,
        equipSlot: "weapon",
        unlockLevel: 13,
        weaponStats: { damageBonus: 40 },
        armorStats: null
    },
    {
        id: "sa80",
        name: "SA80",
        type: "weapon",
        category: "assault_rifle",
        price: 16100,
        equipSlot: "weapon",
        unlockLevel: 14,
        weaponStats: { damageBonus: 41 },
        armorStats: null
    },
    {
        id: "galil",
        name: "Galil",
        type: "weapon",
        category: "assault_rifle",
        price: 16250,
        equipSlot: "weapon",
        unlockLevel: 14,
        weaponStats: { damageBonus: 42 },
        armorStats: null
    },
    {
        id: "sig-sg-550",
        name: "SIG SG 550",
        type: "weapon",
        category: "assault_rifle",
        price: 16400,
        equipSlot: "weapon",
        unlockLevel: 14,
        weaponStats: { damageBonus: 43 },
        armorStats: null
    },
    {
        id: "tavor-tar-21",
        name: "Tavor TAR-21",
        type: "weapon",
        category: "assault_rifle",
        price: 18000,
        equipSlot: "weapon",
        unlockLevel: 15,
        weaponStats: { damageBonus: 44 },
        armorStats: null
    },
    {
        id: "qbz-95",
        name: "QBZ-95",
        type: "weapon",
        category: "assault_rifle",
        price: 18150,
        equipSlot: "weapon",
        unlockLevel: 15,
        weaponStats: { damageBonus: 45 },
        armorStats: null
    },
    {
        id: "an-94",
        name: "AN-94",
        type: "weapon",
        category: "assault_rifle",
        price: 18300,
        equipSlot: "weapon",
        unlockLevel: 15,
        weaponStats: { damageBonus: 46 },
        armorStats: null
    },
    {
        id: "stg-44",
        name: "StG 44",
        type: "weapon",
        category: "assault_rifle",
        price: 20000,
        equipSlot: "weapon",
        unlockLevel: 16,
        weaponStats: { damageBonus: 47 },
        armorStats: null
    },
    {
        id: "cz-805-bren",
        name: "CZ 805 Bren",
        type: "weapon",
        category: "assault_rifle",
        price: 20150,
        equipSlot: "weapon",
        unlockLevel: 16,
        weaponStats: { damageBonus: 48 },
        armorStats: null
    },
    {
        id: "remington-700",
        name: "Remington 700",
        type: "weapon",
        category: "sniper",
        price: 20400,
        equipSlot: "weapon",
        unlockLevel: 16,
        weaponStats: { damageBonus: 49 },
        armorStats: null
    },
    {
        id: "m24-sniper-weapon-system",
        name: "M24 Sniper Weapon System",
        type: "weapon",
        category: "sniper",
        price: 22300,
        equipSlot: "weapon",
        unlockLevel: 17,
        weaponStats: { damageBonus: 50 },
        armorStats: null
    },
    {
        id: "m40-rifle",
        name: "M40 rifle",
        type: "weapon",
        category: "sniper",
        price: 22450,
        equipSlot: "weapon",
        unlockLevel: 17,
        weaponStats: { damageBonus: 51 },
        armorStats: null
    },
    {
        id: "dragunov-svd",
        name: "Dragunov SVD",
        type: "weapon",
        category: "sniper",
        price: 22600,
        equipSlot: "weapon",
        unlockLevel: 17,
        weaponStats: { damageBonus: 52 },
        armorStats: null
    },
    {
        id: "accuracy-international-awm",
        name: "Accuracy International AWM",
        type: "weapon",
        category: "sniper",
        price: 24700,
        equipSlot: "weapon",
        unlockLevel: 18,
        weaponStats: { damageBonus: 53 },
        armorStats: null
    },
    {
        id: "cheytac-m200-intervention",
        name: "CheyTac M200 Intervention",
        type: "weapon",
        category: "sniper",
        price: 24900,
        equipSlot: "weapon",
        unlockLevel: 18,
        weaponStats: { damageBonus: 54 },
        armorStats: null
    },
    {
        id: "mcmillan-tac-50",
        name: "McMillan TAC-50",
        type: "weapon",
        category: "sniper",
        price: 25100,
        equipSlot: "weapon",
        unlockLevel: 18,
        weaponStats: { damageBonus: 55 },
        armorStats: null
    },
    {
        id: "barrett-m82",
        name: "Barrett M82",
        type: "weapon",
        category: "sniper",
        price: 27400,
        equipSlot: "weapon",
        unlockLevel: 19,
        weaponStats: { damageBonus: 56 },
        armorStats: null
    },
    {
        id: "barrett-m107",
        name: "Barrett M107",
        type: "weapon",
        category: "sniper",
        price: 27600,
        equipSlot: "weapon",
        unlockLevel: 19,
        weaponStats: { damageBonus: 57 },
        armorStats: null
    },
    {
        id: "l115a3",
        name: "L115A3",
        type: "weapon",
        category: "sniper",
        price: 27800,
        equipSlot: "weapon",
        unlockLevel: 19,
        weaponStats: { damageBonus: 58 },
        armorStats: null
    },
    {
        id: "drone",
        name: "Drone",
        type: "weapon",
        category: "special",
        price: 30400,
        equipSlot: "weapon",
        unlockLevel: 20,
        weaponStats: { damageBonus: 59 },
        armorStats: null
    },
    {
        id: "c4",
        name: "C4",
        type: "weapon",
        category: "special",
        price: 30700,
        equipSlot: "weapon",
        unlockLevel: 20,
        weaponStats: { damageBonus: 60 },
        armorStats: null
    },
    {
        id: "rpg",
        name: "RPG",
        type: "weapon",
        category: "special",
        price: 31000,
        equipSlot: "weapon",
        unlockLevel: 20,
        weaponStats: { damageBonus: 61 },
        armorStats: null
    },
    {
        id: "javelin",
        name: "Javelin",
        type: "weapon",
        category: "special",
        price: 33800,
        equipSlot: "weapon",
        unlockLevel: 21,
        weaponStats: { damageBonus: 62 },
        armorStats: null
    },
    {
        id: "tomehawk",
        name: "Tomehawk",
        type: "weapon",
        category: "special",
        price: 34100,
        equipSlot: "weapon",
        unlockLevel: 21,
        weaponStats: { damageBonus: 63 },
        armorStats: null
    }
];
exports.weaponUnlockCatalog = defaultWeaponUnlockCatalog.map((item) => ({ ...item }));
